### ISSUE TITLE
Race condition in model relation

### ISSUE THREAD

**Issue by mcauto** [go-gorm/gorm#2417]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go version go1.11.2 linux/amd64

### Which database and its version are you using?
using [sqlmock](https://github.com/DATA-DOG/go-sqlmock)

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package repo_test

import (
	"database/sql/driver"
	"fmt"
	"log"
	"path/filepath"
	"reflect"
	"regexp"
	"runtime"
	"strings"
	"testing"

	sqlmock "github.com/DATA-DOG/go-sqlmock"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	"github.com/stretchr/testify/assert"
)

type User struct {
	ID          uint32 `gorm:"column:Seqno;type:int(10);primary_key:true;AUTO_INCREMENT"`
	Name        string `gorm:"column:Name;type:varchar(20);unique_index:Name_HumanNumber"`
	HumanNumber uint32 `gorm:"column:HumanNumber;type:int(10);unique_index:Name_HumanNumber"`
	Items       []Item `gorm:"foreignkey:UserSeq"`
}

func (user User) TableName() string {
	return "Users"
}

type Item struct {
	ID      uint32 `gorm:"column:Seqno;type:int(10);primary_key:true;AUTO_INCREMENT"`
	UserSeq uint32 `gorm:"column:UserSeq;type:int(10)`
	Name    string `gorm:"column:Name;type:varchar(20)"`
}

func (item Item) TableName() string {
	return "Items"
}

func newDB() (sqlmock.Sqlmock, *gorm.DB) {
	db, mock, err := sqlmock.New()
	if err != nil {
		log.Fatalf("can't create sqlmock: %s", err)
	}

	gormDB, gerr := gorm.Open("mysql", db)
	if gerr != nil {
		log.Fatalf("can't open gorm connection: %s", err)
	}
	gormDB.LogMode(true)

	return mock, gormDB.Set("gorm:update_column", true)
}

func checkMock(t *testing.T, mock sqlmock.Sqlmock) {
	if err := mock.ExpectationsWereMet(); err != nil {
		t.Errorf("there were unfulfilled expections: %s", err)
	}
}

type testQueryFunc func(t *testing.T, mock sqlmock.Sqlmock, conn *gorm.DB)

func TestQueries(t *testing.T) {
	funcs := []testQueryFunc{
		testUpdate,
		testFind,
		testFindByIndex,
	}
	for _, f := range funcs {
		f := f // closure
		funcName := runtime.FuncForPC(reflect.ValueOf(f).Pointer()).Name()
		funcName = filepath.Ext(funcName)
		funcName = strings.TrimPrefix(funcName, ".")
		t.Run(funcName, func(t *testing.T) {
			t.Parallel()
			m, db := newDB()
			defer checkMock(t, m)
			f(t, m, db)
		})
	}
}

func wrapRegex(s string) string {
	return fmt.Sprintf("^%s$", regexp.QuoteMeta(s))
}

func testUpdate(t *testing.T, mock sqlmock.Sqlmock, conn *gorm.DB) {
	user := &User{
		ID:          1,
		Name:        "tester",
		HumanNumber: 1234,
	}
	query := "UPDATE `Users` SET `HumanNumber` = ?, `Name` = ?, `Seqno` = ? WHERE `Users`.`Seqno` = ?"
	args := []driver.Value{
		user.HumanNumber, user.Name, user.ID, user.ID,
	}
	mock.ExpectExec(wrapRegex(query)).
		WithArgs(args...).
		WillReturnResult(sqlmock.NewResult(0, 1))

	u := map[string]interface{}{
		"Seqno":       user.ID,
		"Name":        user.Name,
		"HumanNumber": user.HumanNumber,
	}
	err := conn.Model(user).Updates(u).Error
	switch err {
	case gorm.ErrRecordNotFound:
	default:
		assert.Nil(t, err)
	}
}
func testFindByIndex(t *testing.T, mock sqlmock.Sqlmock, conn *gorm.DB) {
	user := &User{
		ID:          1,
		Name:        "tester",
		HumanNumber: 1234,
	}
	rows := sqlmock.NewRows([]string{"HumanNumber", "Seqno", "Name"}).AddRow(user.HumanNumber, user.ID, user.Name)
	query := "SELECT * FROM `Users` WHERE (Name = ? AND HumanNumber = ?)"

	mock.ExpectQuery(wrapRegex(query)).
		WithArgs(user.Name, user.HumanNumber).
		WillReturnRows(rows)
	u := &User{}
	err := conn.Where("Name = ? AND HumanNumber = ?", user.Name, user.HumanNumber).Find(u).Error
	fmt.Println(rows)
	fmt.Println(u)
	assert.NoError(t, err)
}

func testFind(t *testing.T, mock sqlmock.Sqlmock, conn *gorm.DB) {
	user := &User{
		ID:          1,
		Name:        "tester",
		HumanNumber: 1234,
	}
	rows := sqlmock.NewRows([]string{"HumanNumber", "Seqno", "Name"}).AddRow(user.HumanNumber, user.ID, user.Name)
	query := "SELECT * FROM `Users` WHERE (Seqno = ?)"

	mock.ExpectQuery(wrapRegex(query)).
		WithArgs(user.ID).
		WillReturnRows(rows)

	u := &User{}
	err := conn.Where("Seqno = ?", user.ID).Find(u).Error
	fmt.Println(rows)
	fmt.Println(u)
	assert.NoError(t, err)
}
```

## Result
``` bash
go test -v -race
=== RUN   TestQueries
=== RUN   TestQueries/testUpdate
=== PAUSE TestQueries/testUpdate
=== RUN   TestQueries/testFind
=== PAUSE TestQueries/testFind
=== RUN   TestQueries/testFindByIndex
=== PAUSE TestQueries/testFindByIndex
=== CONT  TestQueries/testUpdate
=== CONT  TestQueries/testFindByIndex
==================
WARNING: DATA RACE
Write at 0x00c0000a7380 by goroutine 7:
  repo/vendor/github.com/jinzhu/gorm.(*Scope).GetModelStruct.func1()
      /root/go/src/repo/vendor/github.com/jinzhu/gorm/model_struct.go:423 +0x1d4a
  repo/vendor/github.com/jinzhu/gorm.(*Scope).GetModelStruct()
      /root/go/src/repo/vendor/github.com/jinzhu/gorm/model_struct.go:630 +0x1e9c
  repo/vendor/github.com/jinzhu/gorm.(*Scope).Fields()
      /root/go/src/repo/vendor/github.com/jinzhu/gorm/scope.go:114 +0x106
  repo/vendor/github.com/jinzhu/gorm.(*Scope).FieldByName()
      /root/go/src/repo/vendor/github.com/jinzhu/gorm/scope.go:141 +0x6b
  repo/vendor/github.com/jinzhu/gorm.(*Scope).updatedAttrsWithValues()
      /root/go/src/repo/vendor/github.com/jinzhu/gorm/scope.go:914 +0x18a
  repo/vendor/github.com/jinzhu/gorm.assignUpdatingAttributesCallback()
      /root/go/src/repo/vendor/github.com/jinzhu/gorm/callback_update.go:26 +0x8c
  repo/vendor/github.com/jinzhu/gorm.(*Scope).callCallbacks()
      /root/go/src/repo/vendor/github.com/jinzhu/gorm/scope.go:867 +0xc3
  repo/vendor/github.com/jinzhu/gorm.(*DB).Updates()
      /root/go/src/repo/vendor/github.com/jinzhu/gorm/main.go:426 +0x175
  repo_test.testUpdate()
      /root/go/src/repo/repo_test.go:107 +0x6ce
  repo_test.TestQueries.func1()
      /root/go/src/repo/repo_test.go:79 +0xd2
  testing.tRunner()
      /usr/lib/golang/src/testing/testing.go:827 +0x162

Previous write at 0x00c0000a7380 by goroutine 9:
  repo/vendor/github.com/jinzhu/gorm.(*Scope).GetModelStruct.func1()
      /root/go/src/repo/vendor/github.com/jinzhu/gorm/model_struct.go:423 +0x1d4a
  repo/vendor/github.com/jinzhu/gorm.(*Scope).GetModelStruct()
      /root/go/src/repo/vendor/github.com/jinzhu/gorm/model_struct.go:630 +0x1e9c
  repo/vendor/github.com/jinzhu/gorm.(*Scope).Fields()
      /root/go/src/repo/vendor/github.com/jinzhu/gorm/scope.go:114 +0x106
  repo/vendor/github.com/jinzhu/gorm.(*Scope).FieldByName()
      /root/go/src/repo/vendor/github.com/jinzhu/gorm/scope.go:141 +0x6b
  repo/vendor/github.com/jinzhu/gorm.(*Scope).whereSQL()
      /root/go/src/repo/vendor/github.com/jinzhu/gorm/scope.go:714 +0x93
  repo/vendor/github.com/jinzhu/gorm.(*Scope).CombinedConditionSql()
      /root/go/src/repo/vendor/github.com/jinzhu/gorm/scope.go:345 +0x7b
  repo/vendor/github.com/jinzhu/gorm.(*Scope).prepareQuerySQL()
      /root/go/src/repo/vendor/github.com/jinzhu/gorm/scope.go:845 +0x110
  repo/vendor/github.com/jinzhu/gorm.queryCallback()
      /root/go/src/repo/vendor/github.com/jinzhu/gorm/callback_query.go:59 +0x261
  repo/vendor/github.com/jinzhu/gorm.(*Scope).callCallbacks()
      /root/go/src/repo/vendor/github.com/jinzhu/gorm/scope.go:867 +0xc3
  repo/vendor/github.com/jinzhu/gorm.(*DB).Find()
      /root/go/src/repo/vendor/github.com/jinzhu/gorm/main.go:331 +0x11f
  repo_test.testFindByIndex()
      /root/go/src/repo/repo_test.go:127 +0x6fd
  repo_test.TestQueries.func1()
      /root/go/src/repo/repo_test.go:79 +0xd2
  testing.tRunner()
      /usr/lib/golang/src/testing/testing.go:827 +0x162

Goroutine 7 (running) created at:
  testing.(*T).Run()
      /usr/lib/golang/src/testing/testing.go:878 +0x650
  repo_test.TestQueries()
      /root/go/src/repo/repo_test.go:75 +0xbc
  testing.tRunner()
      /usr/lib/golang/src/testing/testing.go:827 +0x162

Goroutine 9 (running) created at:
  testing.(*T).Run()
      /usr/lib/golang/src/testing/testing.go:878 +0x650
  repo_test.TestQueries()
      /root/go/src/repo/repo_test.go:75 +0xbc
  testing.tRunner()
      /usr/lib/golang/src/testing/testing.go:827 +0x162
==================

(/root/go/src/repo/repo_test.go:107)
[2019-04-23 14:07:44]  [2.24ms]  UPDATE `Users` SET `HumanNumber` = 1234, `Name` = 'tester', `Seqno` = 1  WHERE `Users`.`Seqno` = 1 
[1 rows affected or returned ]

(/root/go/src/repo/repo_test.go:127)
[2019-04-23 14:07:44]  [3.32ms]  SELECT * FROM `Users`  WHERE (Name = 'tester' AND HumanNumber = 1234)
[1 rows affected or returned ]
&{{} [HumanNumber Seqno Name] [[1234 1 tester]] 2 map[] <nil>}
=== CONT  TestQueries/testFind
&{1 tester 1234 []}

(/root/go/src/repo/repo_test.go:147)
[2019-04-23 14:07:44]  [1.22ms]  SELECT * FROM `Users`  WHERE (Seqno = 1)
[1 rows affected or returned ]
&{{} [HumanNumber Seqno Name] [[1234 1 tester]] 2 map[] <nil>}
&{1 tester 1234 []}
--- FAIL: TestQueries (0.00s)
    --- FAIL: TestQueries/testUpdate (0.01s)
        testing.go:771: race detected during execution of test
    --- FAIL: TestQueries/testFindByIndex (0.01s)
        testing.go:771: race detected during execution of test
    --- PASS: TestQueries/testFind (0.00s)
FAIL
exit status 1
FAIL    repo    0.038s
```

**Comment by rubensayshi** [comment]
I think this is fixed by https://github.com/jinzhu/gorm/pull/2721

**Comment by j16r** [comment]
I'm still seeing it: https://circleci.com/gh/smartcontractkit/chainlink/74327?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by rubensayshi** [comment]
hmm, ye that appears to be a different one on `field.Relationship`
