### ISSUE TITLE
sql: expected 2 destination arguments in Scan, not 1

### ISSUE THREAD

**Issue by lihaotian0607** [go-gorm/gorm#3072]
### 版本: v0.2.5

```go
var rows []AuthRole
var count int64
err := m.db.Select([]string{"id", "name"}).Find(&rows).Count(&count).Error

fmt.Println(err, count, rows)
```

生成的sql:
```
SELECT `id`,`name` FROM `auth_roles`

SELECT `id`,`name` FROM `auth_roles`
sql: expected 2 destination arguments in Scan, not 1 0 [{<nil> 1 11 0}]
```

**Comment by lihaotian0607** [comment]
![image](https://user-images.githubusercontent.com/32523475/85345641-8b144400-b525-11ea-8640-63f18bc4d9ac.png)

貌似只判断了`tx.Statement.Selects`是0和1的情况

**Comment by jinzhu** [comment]
Upgrade to v0.2.13 should fix this.

**Comment by ap-in-git** [comment]
@jinzhu 
I am using version 0.2.25 I am still seeing this error in the mysql driver .

When I have this code it gets error .
`
func countRecords(db *gorm.DB, anyType interface{}, done chan bool, count *int64) {
	db.Model(anyType).Count(count)
}
`

But when I do this I don't get that error
`
func countRecords(db *gorm.DB, anyType interface{}, done chan bool, count *int64) {
	db.Debug().Model(anyType).Count(count)
}

`

**Comment by jinzhu** [comment]
@ap-in-git please create an issue with reproducible PR link
